name: meepshoptest
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  freezed_annotation: ^2.4.4
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  injectable: ^2.5.0
  auto_route: ^8.2.0
  flutter_screenutil: ^5.9.3
  fpdart: ^1.1.0
  json_annotation: ^4.9.0
  gap: ^3.0.1
  nb_utils: ^6.1.2
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  uuid: ^4.3.3
  intl: ^0.18.1
  equatable: ^2.0.5
  socket_io_client: ^2.0.3
  formz: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.3
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  auto_route_generator: ^8.0.0
  injectable_generator: ^2.6.2
  mockito: ^5.4.4

flutter:
  uses-material-design: true
